// GENERATED by scripts/extract-spell-tables.ts — do not edit by hand.
// Run `npm run gen:spell-tables` to refresh.

/**
 * Free-access slot levels of each magic path: the levels its printed spell list
 * does not cover. One per decade in major paths (10 total), two in minor ones
 * (20 total). Only the slots at or below the path's level are available.
 */
export const FREE_ACCESS_LEVELS: Readonly<Record<string, readonly number[]>> = {
  "Luz": [4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
  "Oscuridad": [4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
  "Fuego": [4, 8, 14, 18, 24, 28, 34, 38, 44, 48, 54, 58, 64, 68, 74, 78, 84, 88, 94, 98],
  "Agua": [4, 8, 14, 18, 24, 28, 34, 38, 44, 48, 54, 58, 64, 68, 74, 78, 84, 88, 94, 98],
  "Aire": [4, 8, 14, 18, 24, 28, 34, 38, 44, 48, 54, 58, 64, 68, 74, 78, 84, 88, 94, 98],
  "Tierra": [4, 8, 14, 18, 24, 28, 34, 38, 44, 48, 54, 58, 64, 68, 74, 78, 84, 88, 94, 98],
  "Creación": [4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
  "Destrucción": [4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
  "Esencia": [4, 8, 14, 18, 24, 28, 34, 38, 44, 48, 54, 58, 64, 68, 74, 78, 84, 88, 94, 98],
  "Ilusión": [4, 8, 14, 18, 24, 28, 34, 38, 44, 48, 54, 58, 64, 68, 74, 78, 84, 88, 94, 98],
  "Nigromancia": [4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
};

/**
 * Levels a sub-path's ten spells occupy — the first slot of each decade. Linking
 * a sub-path therefore consumes 10 slots: all of them in a major path, half of
 * them in a minor one, which keeps its second slot per decade free.
 */
export const SUB_PATH_LEVELS: readonly number[] = [4, 14, 24, 34, 44, 54, 64, 74, 84, 94];

/** The `magicPath` label of the general Libre Acceso pool (not a path item). */
export const FREE_ACCESS_LABEL = "Libre acceso";
